import React from "react";
import "./style.css";

//Images
import smPageBG from "../../assets/images/smPageBG.svg";
import policyPointIcon from "../../assets/images/policyPointIcon.svg";

//components
import NavBar from "../../components/NavBar";
import Footer from "../../components/Footer";

interface NavProps {
  currentNav: string;
  setCurrentNav: React.Dispatch<React.SetStateAction<string>>;
}

export default function TermsOfUse({ setCurrentNav, currentNav }: NavProps) {
  setCurrentNav("");
  return (
    <>
      <div className="SMHeroBox">
        <NavBar setCurrentNav={setCurrentNav} currentNav={currentNav} />
        <img src={smPageBG} className="smPageBG" />
      </div>
      <div className="policyMainBox">
        <p className="sectionHeader">Terms Of Use</p>
        <p className="policySubText">
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <div className="termsListBox">
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              The terms ‘We’, ‘Us’& ‘Our’ shall mean the Website and/or the
              Company, as the context so requires.
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              For the purpose of this Privacy Policy (“Policy”), wherever the
              context so requires,
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              Lorem ipsum dolor sit amet consectetur. Ac nisl gravida posuere
              dui volutpat adipiscing facilisis nulla. Sit maecenas.
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              The Parties expressly agree that the Company retains the sole and
              exclusive right to amend or modify the Policy and the
              aforementioned Terms without any prior permission or intimation to
              the User, and the 
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              The term ‘You’ &‘User’ shall mean any legal person or entity
              accessing or using the services provided on this Website, who is
              competent to enter into binding contracts, as per the provisions
              of the Indian Contract Act, 1872
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              The terms ‘Party’ & ‘Parties’ shall respectively be used to refer
              to the User and the Company individually and collectively, as the
              context so requires.
            </p>
          </div>
          <div className="policyPoint">
            <img src={policyPointIcon} alt="" />
            <p>
              The User is aware that the Company/Website may automatically track
              certain information about the User based upon the User’s IP
              address and the User’s behaviour on the Website, and the User
              expressly consents to the same.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
